#!/bin/bash

# field separator to the new line
IFS=$'\n'

for line in $(git status -s)
do
  # if added or modified
  if [[ $line == A* || $line == M* ]]
  then
    if [[ $line == *.rs ]]
    then
      cargo +nightly fmt $(pwd)/${line:3}
      cargo +nightly clippy -Z unstable-options -- -D warnings $(pwd)/${line:3}

      git add $(pwd)/${line:3}
    fi
  fi
done
