[package]
name = "tempmail"
version = "0.1.0"
authors = ["Dilshad <dilshadplayingminecraft@outlook.com>"]
edition = "2021"

[dependencies]
reqwest = "0.11.18"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
