[package]
name = "tempmail"
version = "0.1.0"
description = "Simplify temporary email management and interaction, including message retrieval and attachment downloads."
authors = ["Dilshad <dilshadplayingminecraft@outlook.com>"]
edition = "2021"
license = "MIT"
documentation = "https://docs.rs/tempmail"
repository = "https://github.com/a-rustacean/tempmail"

[dependencies]
chrono = "0.4.26"
rand = "0.8.5"
reqwest = "0.11.18"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
tokio = { version = "1.31.0", features = ["full"] }
