[package]
name = "tempmail"
version = "0.2.4"
description = "Simplify temporary email management and interaction, including message retrieval and attachment downloads."
authors = ["Dilshad <a-rustacean@outlook.com>"]
edition = "2021"
license = "MIT"
documentation = "https://docs.rs/tempmail"
repository = "https://github.com/a-rustacean/tempmail"
categories = ["email", "api", "tempmail"]
keywords = ["tempmail", "api", "email", "1secmail", "wrapper"]

[dependencies]
chrono = "0.4.26"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
reqwest = { version = "0.11.18", features = ["json"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rand = "0.8.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.64"
