name: Lint and Check Formatting

on:
  push:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "full"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Rust
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-lint

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, clippy

      - name: Lint
        run: cargo +nightly clippy --all -Z unstable-options -- -D warnings

      - name: Check Formatting
        run: cargo +nightly fmt --all --check
