name: Typo

on:
  push:
    branches: ["*", "*/*", "**"]
  pull_request:
    branches: ["*", "*/*", "**"]
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "full"

jobs:
  typo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Typos
        uses: crate-ci/typos@master
